name: CI

on:
  pull_request:

  push:
    branches: [ master ]

env:
  CODECOV_TOKEN: 8d6689bc-569a-40d4-ae0e-a3adbf3e5181

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby:
          - 2.7
          - '3.0'
          - 3.1
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake rubospec